version: 2.1

#
# Jobs
#

jobs:
  test:
    macos:
      xcode: 16.4
    steps:
      - checkout
      - run:
          name: Test
          command: |
            set -o pipefail && xcodebuild -project LoopKit.xcodeproj -scheme Shared build -destination 'OS=18.5,name=iPhone 16' test | xcpretty
      - store_test_results:
          path: test_output
  package:
    macos:
      xcode: 16.4
    steps:
      - checkout
      - run: rm -rf LoopKit.xcodeproj
      - run:
          name: Build LoopKit Package
          command: |
            set -o pipefail && xcodebuild build -scheme LoopKit -sdk iphonesimulator18.5 -destination "OS=18.5,name=iPhone 16" | xcpretty
      - run:
          name: Build LoopKitUI Package
          command: |
            set -o pipefail && xcodebuild build -scheme LoopKitUI -sdk iphonesimulator18.5 -destination "OS=18.5,name=iPhone 16" | xcpretty
#
# Workflows
#

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
      - package

